In [ ]:
# 19-Crie uma matriz 2x2 e exiba seus elementos em formato de matriz.
import numpy as np
def mostrarMatriz():
  matriz = np.array([[1,2],[3,4]])
  return matriz
mostrarMatriz()

array([[1, 2],
       [3, 4]])

In [ ]:
# 20-Solicite ao usuário que insira os elementos de uma matriz 3x3 e exiba a matriz
# formatada.
import numpy as np
def inserirElemento():
  matriz = np.array([[0, 1, 3],
                    [9, 8, 6],
                    [34, 24, 10]])

  print("Matriz original:")
  print(matriz)

  for linha in range(matriz.shape[0]):
      for coluna in range(matriz.shape[1]):
          valor = int(input(f'Digite o valor para a posição ({linha}, {coluna}): '))
          matriz[linha, coluna] = valor

  print("\nMatriz atualizada:")
  print(matriz)

inserirElemento()

Matriz original:
[[ 0  1  3]
 [ 9  8  6]
 [34 24 10]]
Digite o valor para a posição (0, 0): 5
Digite o valor para a posição (0, 1): 10
Digite o valor para a posição (0, 2): 15
Digite o valor para a posição (1, 0): 20
Digite o valor para a posição (1, 1): 25
Digite o valor para a posição (1, 2): 30
Digite o valor para a posição (2, 0): 35
Digite o valor para a posição (2, 1): 40
Digite o valor para a posição (2, 2): 45

Matriz atualizada:
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [ ]:
matriz = []

# Pede a quantidade de linhas
linhas = int(input('Digite a quantidade de linhas:'))

# Pede a quantidade de colunas apenas uma vez
colunas = int(input("Digite a quantidade de colunas:"))

# Preenche a matriz com as linhas e colunas fornecidas
for l in range(linhas):
    linha = []  # Cria uma nova lista para a linha
    for c in range(colunas):
        # Pede os valores para preencher a linha
        valor = int(input(f'Digite o valor para a posição ({l},{c}): '))
        linha.append(valor)  # Adiciona o valor à linha
    matriz.append(linha)  # Adiciona a linha completa à matriz

# Exibe a matriz final
print("\nMatriz preenchida:")
for linha in matriz:
    print(linha)


Digite a quantidade de linhas:2
Digite a quantidade de colunas:2
Digite o valor para a posição (0,0): 1
Digite o valor para a posição (0,1): 2
Digite o valor para a posição (1,0): 3
Digite o valor para a posição (1,1): 5

Matriz preenchida:
[1, 2]
[3, 5]


In [ ]:
# 21-Peça ao usuário que insira duas matrizes 2x2 e exiba a matriz resultante da
# soma das duas.

import numpy as np
matriz1 = np.array([[0, 0],
                    [0, 0]])
matriz2 = np.array([[0, 0],
                    [0, 0]])
def somaMatriz(m1,m2):
  soma = m1 + m2
  return print(f'\nEssa é a soma das matriz \n{soma}')
  print("\nMatriz atualizada:")
  print(soma)

def inserirPrimeiraMatriz(matriz):
  print("Digite os valores para criar a primeira matriz:")
  print(matriz)

  for linha in range(matriz.shape[0]):
      for coluna in range(matriz.shape[1]):
          valor = int(input(f'Digite o valor para a posição ({linha}, {coluna}): '))
          matriz[linha, coluna] = valor
      matriz[linha, coluna] = valor

def inserirSegundaMatriz(matriz):

  print("Digite os valores para criar a segunda matriz:")
  print(matriz)

  for linha in range(matriz.shape[0]):
      for coluna in range(matriz.shape[1]):
          valor = int(input(f'Digite o valor para a posição ({linha}, {coluna}): '))
          matriz[linha, coluna] = valor
      matriz[linha, coluna] = valor



inserirPrimeiraMatriz(matriz1)
inserirSegundaMatriz(matriz2)
somaMatriz(matriz1,matriz2)

Digite os valores para criar a primeira matriz:
[[0 0]
 [0 0]]
Digite o valor para a posição (0, 0): 5
Digite o valor para a posição (0, 1): 5
Digite o valor para a posição (1, 0): 5
Digite o valor para a posição (1, 1): 5
Digite os valores para criar a segunda matriz:
[[0 0]
 [0 0]]
Digite o valor para a posição (0, 0): 1
Digite o valor para a posição (0, 1): 2
Digite o valor para a posição (1, 0): 3
Digite o valor para a posição (1, 1): 4

Essa é a soma das matriz 
[[6 7]
 [8 9]]


In [ ]:
# 22-Crie uma função que receba um número e retorne o dobro dele.
def dobroNum(num):
  dobro = num *2
  return print(f'O dobro de {num} é {dobro}')
while True:
  number = input("Digite um número para ver o dobro dele ou digite 's' para sair:")
  if number == 's':
    print("MUITO ORBIGADA \nATÉ A PRÓXIMA")
    break
  dobroNum(int(number))

Digite um número para ver o dobro dele ou digite 's' para sair:5
O dobro de 5 é 10
Digite um número para ver o dobro dele ou digite 's' para sair:3
O dobro de 3 é 6
Digite um número para ver o dobro dele ou digite 's' para sair:2
O dobro de 2 é 4
Digite um número para ver o dobro dele ou digite 's' para sair:s
MUITO ORBIGADA 
 ATÉ A PRÓXIMA


In [ ]:
# 23-Crie uma função que receba um número e informe se ele é par ou ímpar.
def imparPar(num):
  if (num %2) == 0:
    print(f'{num} é par')
  else:
    print(f'{num} é impar')

while True:
  number = input("Digite um número para saber se é par ou impar ou digite 's' para sair:")
  if number == 's':
    print("MUITO ORBIGADA \nATÉ A PRÓXIMA")
    break
  imparPar(int(number))

Digite um número para saber se é par ou impar ou digite 's' para sair:5
5 é impar
Digite um número para saber se é par ou impar ou digite 's' para sair:10
10 é par
Digite um número para saber se é par ou impar ou digite 's' para sair:100
100 é par
Digite um número para saber se é par ou impar ou digite 's' para sair:1501
1501 é impar
Digite um número para saber se é par ou impar ou digite 's' para sair:50132348556
50132348556 é par
Digite um número para saber se é par ou impar ou digite 's' para sair:s
MUITO ORBIGADA 
ATÉ A PRÓXIMA


In [ ]:
# 24-Crie uma função que receba uma lista de números e retorne a soma de todos
# # os números ímpares da lista.
def somaListaImpar(lista):
  sumI=0
  for i in lista:
    if (i%2) != 0:
      sumI += i
  print(sumI)

somaListaImpar([3,6,9,12,15])

27


In [ ]:
# 25-Peça ao usuário para inserir um número e calcule sua raiz quadrada usando a
# biblioteca math.
import math #é uma bablioteca mt utilizada para cálculos
def raizQuadrada(num):
  # sqrt = a função que calcula a raiz
  raiz = math.sqrt(num)
  return print(f"A raiz quadrada de {num} é {raiz}")

while True:
  number = input("Digite um número para saber a sua raiz ou digite 's' para sair:")
  if number == 's':
    print("MUITO ORBIGADA \nATÉ A PRÓXIMA")
    break
  raizQuadrada(int(number))

Digite um número para saber a sua raiz ou digite 's' para sair:2
A raiz quadrada de 2 é 1.4142135623730951
Digite um número para saber a sua raiz ou digite 's' para sair:4
A raiz quadrada de 4 é 2.0
Digite um número para saber a sua raiz ou digite 's' para sair:6
A raiz quadrada de 6 é 2.449489742783178
Digite um número para saber a sua raiz ou digite 's' para sair:9
A raiz quadrada de 9 é 3.0
Digite um número para saber a sua raiz ou digite 's' para sair:16
A raiz quadrada de 16 é 4.0
Digite um número para saber a sua raiz ou digite 's' para sair:25
A raiz quadrada de 25 é 5.0
Digite um número para saber a sua raiz ou digite 's' para sair:s
MUITO ORBIGADA 
ATÉ A PRÓXIMA


In [9]:
# 26-Peça ao usuário para inserir uma data no formato dd/mm/aaaa e exiba o dia da
# semana correspondente.
import datetime

dias_da_semana = ["segunda-feira", "terça-feira", "quarta-feira", "quinta-feira", "sexta-feira", "sábado", "domingo"]

data_input = input("Digite uma data no formato dd/mm/aaaa: ")

data = datetime.datetime.strptime(data_input, '%d/%m/%Y')

numero_dia = data.weekday()

print(f"O dia da semana correspondente é: {dias_da_semana[numero_dia]}")


Digite uma data no formato dd/mm/aaaa: 26/12/2007
O dia da semana correspondente é: quarta-feira


In [20]:
# 27-Solicite ao usuário um número e exiba um valor aleatório entre 1 e esse
# número.
import random

num = int(input("Digite um número: "))
numero_aleatorio = random.randint(1, num)

print(numero_aleatorio)
print(num)


Digite um número: 10
10
10


In [21]:
# 28-Use o módulo random para gerar uma lista com 5 números aleatórios entre 1 e
# 100 e exibi-los.

listaNum = []
for i in range(5):
  listaNum.append(random.randint(1,100))
print(listaNum)

[97, 78, 12, 79, 13]


In [34]:
# 29-Simule o lançamento de um dado (números de 1 a 6) e exiba o resultado após
# uma pausa de 2 segundos.
import time

while True:
    print("O dado foi jogado e o número que saiu foi: ")
    numero_dado = random.randint(1, 6)

    time.sleep(2.0)
    print(numero_dado)

    dnovo = input("Deseja jogar o dado de novo? (s/n): ")
    if dnovo.lower() != "s":
      break

O dado foi jogado e o número que saiu foi: 
4
Deseja jogar o dado de novo? (s/n): s
O dado foi jogado e o número que saiu foi: 
6
Deseja jogar o dado de novo? (s/n): n


In [37]:
# 30-Crie um programa que crie e escreva a frase "Python é incrível!" em um arquivo
# chamado texto.txt.
arquivo = open("texto.txt", "w")
arquivo.write("Python é incrível!")
arquivo.close()

In [40]:
# 31-Crie um programa que leia o arquivo texto.txt e exiba o conteúdo na tela.
# Abre o arquivo em modo leitura ('r')
arquivo = open("texto.txt", "r")

# Lê todo o conteúdo do arquivo
conteudo = arquivo.read()

# Exibe o conteúdo lido
print(conteudo)

# Fecha o arquivo após a leitura
arquivo.close()


Python é incrível!


In [44]:
# 32-Peça ao usuário para inserir um nome e um telefone e armazene-os em um
# arquivo chamado contatos.txt.
nome = input("Digite seu nome:")
telefone = input("Digite seu telefone")
dados_pessoais = f"Nome: {nome}\nTelefone: {telefone}\n{'-'*30}\n"


arquivo = open("contatos.txt", "w")
arquivo.write(dados_pessoais)
arquivo.close()

Digite seu nome:casa
Digite seu telefone222222222222222222


In [54]:
# 33-Solicite ao usuário um número e tente dividir 100 por ele, tratando o erro caso
# seja digitado zero.
while True:
  numero = int(input("Digite um número: "))

  if numero == 0:
      print("Não é possível dividir 0 por cem.")
  else:
      resultado = 100 / numero
      resultado_formatado = round(resultado,2)
      print(f"O resultado de 100 dividido por {numero} é {resultado_formatado}")


Digite um número: 0
Não é possível dividir 0 por cem.
Digite um número: 67
O resultado de 100 dividido por 67 é 1.49


KeyboardInterrupt: Interrupted by user

In [74]:
# 34-Peça ao usuário para inserir um número e trate possíveis erros de entrada
# (como digitar uma letra no lugar do número).

try:
    numero = int(input("Digite um número: "))
    print(f"O número inserido foi: {numero}")
except ValueError:
    print("Erro: Você não digitou um número válido.")

Digite um número: 6.8
Erro: Você não digitou um número válido.


In [78]:
#35-Solicite ao usuário um número inteiro e trate o erro caso ele tente inserir um
#valor não numérico. Se a entrada for válida, exiba o quadrado do número.
try:
    numero = int(input("Digite um número: "))
    print(f"O número inserido foi: {numero*numero}")
except ValueError:
    print("Erro: Você não digitou um número válido.")

Digite um número: 4
O número inserido foi: 16
